### PR TITLE
--delimiter arg is getting with quotation marks

### LINKED ISSUE #58: --delimiter arg is not getting as a string with quotation marks
## Describe the bug
In case using the `;` as a delimiter, it seems like it is end of the row and another property for CSV is ran as a new command. E2E runner fallout with error `bash: line 1: --header: command not found` because of the problem with getting arg --delimiter. 

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Run e2eRunner with CSV dataset.
2. The delimiter is `;`

### PR DESCRIPTION
**Pull request by HuvarVer**
closes #58

### CODE REVIEW

File: e2eRunner/src/main/scala/za/co/absa/hermes/e2eRunner/E2ERunnerConfig.scala [hunk 1]
```diff
@@ -62,7 +62,7 @@ case class E2ERunnerConfig(rawFormat: String = "parquet",
     rawFormat.toLowerCase() match {
       case "parquet" => "--raw-format parquet"
       case "json" => "--raw-format json"
-      case "csv" => s"--raw-format csv --delimiter $csvDelimiter --header $csvHeader"
+      case "csv" => s"--raw-format csv --delimiter ${'"'}$csvDelimiter${'"'} --header $csvHeader"
```
Comment (Zejnilovic) [inline e2eRunner/src/main/scala/za/co/absa/hermes/e2eRunner/E2ERunnerConfig.scala]:
```suggestion
      case "csv" => s"""--raw-format csv --delimiter "$csvDelimiter" --header $csvHeader"""
```

I think this is called a smart string. `""" something """` and then you can use whatever chars in between them. Look at this [video](https://www.youtube.com/watch?v=RWWotQXltkE)

Comment (HuvarVer) [reply e2eRunner/src/main/scala/za/co/absa/hermes/e2eRunner/E2ERunnerConfig.scala]: 👍 agree, the smart string is nicer solution

**Review by Zejnilovic — APPROVED** [review]
