### PR TITLE
#127 Fix error column being incorrect when ref array is smaller

### LINKED ISSUE #127: When array in reference data has shorter length than in new data then error column is wrong
## Describe the bug
Assume we have column `A` in both reference and new data. Assume `A` in all rows of reference data has the same length `lenARef`, and in all rows of new data `A` has the same length `lenANew`. When `lenARef == lenANew`, comparison works correctly. The same when `lenARef > lenANew` - all "extra" items in column `A` of reference data are marked as difference between datasets (in error column). However, when `lenARef < lenANew` "extra" items in new data are not marked as difference. 

## Expected behaviour
Cases `lenARef > lenANew` and `lenARef < lenANew` should be symmetric.

### PR DESCRIPTION
**Pull request by jakipatryk**
Fixes #127

### CODE REVIEW

**Review by lsulak — COMMENTED** [review]
LGTM - not gonna approve just yet, I want to pull/compile/run tests first, but I don't expect to find anything suspicious

**Review by lsulak — DISMISSED** [review]
- [x]  code reviewed
- [x]  pulled
- [x]  built
- [x]  ran tests

**Review by Zejnilovic — DISMISSED** [review]

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala [hunk 1]
```diff
@@ -53,9 +55,11 @@ object HelperFunctions {
       * @param arrayType ArrayType
       */
     def flattenStructArray(path: String, fieldNamePrefix: String, structField: StructField, arrayType: ArrayType): Unit = {
-      val maxInd = df.agg(max(expr(s"size($path${structField.name})"))).collect()(0)(0).toString.toInt
+      val maxLengths = (Seq(df) ++ Seq(dfsForArraysLength: _*))
+        .map(_.agg(max(expr(s"size($path${structField.name})"))).collect()(0)(0).toString.toInt)
```
Comment (benedeki) [inline utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala]: This is little hard to understand. And why the `.toString.toInt`? Wouldn't `.toInt` be enough?
```suggestion
      val firstRow = 0
      val firstColumn = 0
      val maxLengths = (Seq(df) ++ Seq(dfsForArraysLength: _*))
        .map(_.agg(max(expr(s"size($path${structField.name})"))).collect()(firstRow)(firstColumn).toInt)
```

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala [hunk 2]
```diff
@@ -72,9 +76,11 @@ object HelperFunctions {
     }
 
     def flattenNestedArrays(path: String, fieldNamePrefix: String, arrayType: ArrayType): Unit = {
-      val maxIndexes = df.agg(max(expr(s"size($path)"))).collect()(0)(0).toString.toInt
+      val maxLengths = (Seq(df) ++ Seq(dfsForArraysLength: _*))
+        .map(_.agg(max(expr(s"size($path)"))).collect()(0)(0).toString.toInt)
```
Comment (benedeki) [inline utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala]: Ditto regarding the map function. It can actually be a real function shared by both `flattenStructArray` and `flattenNestedArrays`

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala [hunk 3]
```diff
@@ -38,9 +38,11 @@ object HelperFunctions {
     * especially on a vary big dataframes.
     *
     * @param df A dataframe
+   *  @param dfsForArraysLength DataFrames with the same schema as `df` that are used to
+   *                             flatten arrays with maximum length among `df` and `dfsForArraysLengths`.
     * @return A new dataframe with flat schema.
     */
-  def flattenSchema(df: DataFrame): List[Column] = {
+  def flattenSchema(df: DataFrame, dfsForArraysLength: DataFrame*): List[Column] = {
```
Comment (benedeki) [inline utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala:45]: Wouldn't be enough to name them `otherDfs` instead of `dfsForArraysLength`?

**Review by benedeki — COMMENTED** [review]
Fixes the primary problem.

But I am wondering if the limitation that the array field have to have the same size in all rows couldn't be circumvented by utilizing _spark_hats_ 🤔

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala (hunk 3 above)
Comment (jakipatryk) [reply utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala:45]: I was thinking about that name, or just `dfs`, but these DataFrames are really just to compute arrays length, and names like `dfs` or `otherDfs` kinda suggest to me that schema for these is also flattened (which is not necessary true).

**Comment by jakipatryk** [comment]
> But I am wondering if the limitation that the array field have to have the same size in all rows couldn't be circumvented by utilizing _spark_hats_ 🤔

@benedeki at the first glance on spark-hats I don't really see how. I might be wrong, didn't spend much time thinking about it/checking the library.

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala (hunk 1 above)
Comment (jakipatryk) [reply utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala]: Please let me know if it is easier to understand now, I changed it a little. Can't be just `toInt` as result of `[...](0)(0)` is `Any`, but I cut the expression on `Row` level and used `getInt` instead.

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala (hunk 2 above)
Comment (jakipatryk) [reply utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala]: Yeah, good point. Done

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala (hunk 3 above)
Comment (benedeki) [reply utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala:45]: Fair enough

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala [hunk 4]
```diff
@@ -38,12 +38,21 @@ object HelperFunctions {
...
     val fields = new mutable.ListBuffer[Column]()
     val stringFields = new mutable.ListBuffer[String]()
 
+    def calculateMaxArrayLength(path: String, structField: Option[StructField] = None): Int = {
+      val fullPath = path + structField.map(_.name).getOrElse("")
+      val maxLengths = (Seq(df) ++ Seq(dfsForArraysLength: _*))
+        .map(_.agg(max(expr(s"size($fullPath)"))).collect()(0).getInt(0))
```
Comment (benedeki) [inline utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala]: **Important:*** Realized during night after posting the previous review, that this will throw an exception, if any of the DataFrames is empty.
Probably using `.headOption.getOrElse(0)` is the safe solution.

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala [hunk 5]
```diff
@@ -38,12 +38,21 @@ object HelperFunctions {
...
+   *  @param dfsForArraysLength DataFrames with the same schema as `df` that are used to
+   *                             flatten arrays with maximum length among `df` and `dfsForArraysLengths`.
     * @return A new dataframe with flat schema.
     */
-  def flattenSchema(df: DataFrame): List[Column] = {
+  def flattenSchema(df: DataFrame, dfsForArraysLength: DataFrame*): List[Column] = {
     val fields = new mutable.ListBuffer[Column]()
     val stringFields = new mutable.ListBuffer[String]()
 
+    def calculateMaxArrayLength(path: String, structField: Option[StructField] = None): Int = {
```
Comment (benedeki) [inline utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala:49]: Nice!

**Review by benedeki — DISMISSED** [review]

File: utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala (hunk 4 above)
Comment (jakipatryk) [reply utils/src/main/scala/za/co/absa/hermes/utils/HelperFunctions.scala]: Yeah that's true. Done

**Review by benedeki — APPROVED** [review]
