### PR TITLE
63 make infofile comparison a general atum tool

### LINKED ISSUE #63: Fix usage of properties in InfoFile comparison to be general
## Describe the bug
Fix usage of properties in InfoFile comparison to be general. Currently, it is Enceladus dependant.

## Expected behaviour
Properties should be array based instead of key based

### PR DESCRIPTION
**Pull request by Zejnilovic**
InfoFileComparison module had previously a configuration which would make it Enceladus dependant.
With this update, we would make it only Atum dependant

closes #63

### CODE REVIEW

File: infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/AtumModelUtils.scala [hunk 1]
```diff
@@ -15,20 +15,20 @@
...
-  private val confNameKey = conf.getString("info-file-comparison.atum-models.confNameKey")
-  private val stdAppIdKey = conf.getString("info-file-comparison.atum-models.stdAppIdKey")
-  private val confAppIdKey = conf.getString("info-file-comparison.atum-models.confAppIdKey")
+  private var versionMetaKeys = List.empty[String]
+  private var keysToIgnore = List.empty[String]
+
+  def applyConfig(config: InfoFileComparisonConfig): Unit = {
+    versionMetaKeys = config.versionMetaKeys
+    keysToIgnore = config.keysToIgnore
+  }
```
Comment (yruslan) [inline infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/AtumModelUtils.scala]: It is odd that there are 2 vars and a method `applyConfig()` that is never called. I'll take a look more to maybe come up with more constructive suggestions.

File: infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/ManualConfig.scala [hunk 2]
```diff
@@ -0,0 +1,6 @@
+package za.co.absa.hermes.infoFileComparison.config
+
+class ManualConfig(
```
Comment (yruslan) [inline infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/ManualConfig.scala]: Is this used? An instance of `TypeSafe` config can be created from a `Map` (will add a comment below).

File: infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/TypesafeConfig.scala [hunk 3]
```diff
@@ -0,0 +1,15 @@
+package za.co.absa.hermes.infoFileComparison.config
+
+import com.typesafe.config.{Config, ConfigFactory}
+
+class TypesafeConfig(path: Option[String]) extends InfoFileComparisonConfig {
```
Comment (yruslan) [inline infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/TypesafeConfig.scala]: Just an optional suggestion.
If the constructor parameter is `Config`, then it is up to the user to construct a configuration from a file, from a map or in the default way. And configuration class hierarchy won't be needed. It could be just a case class holding all required configs with a companion object that creates an instance of configuration from a `TypeSafe` `Config`.

**Review by yruslan — COMMENTED** [review]
Looks good. Just a couple of comments.

File: infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/AtumModelUtils.scala (hunk 1 above)
Comment (Zejnilovic) [reply infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/AtumModelUtils.scala]: This is a leftover that shouldn't be here. Will delete

File: infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/ManualConfig.scala (hunk 2 above)
Comment (Zejnilovic) [reply infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/ManualConfig.scala]: ManualConfig was created for the instances when Hermes is used as a library

File: infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/TypesafeConfig.scala (hunk 3 above)
Comment (Zejnilovic) [reply infoFileComparison/src/main/scala/za/co/absa/hermes/infoFileComparison/config/TypesafeConfig.scala]: This is a really nice suggestion. Let me think about it. If I can't find any negatives I will most likely implement.

**Review by yruslan — APPROVED** [review]
Nice!

**Review by HuvarVer — APPROVED** [review]
