### PR TITLE
83 Remove duplicte writing feature

### LINKED ISSUE #83: DatasetComparison method handleDuplicates should be in the Job class
## Describe the bug
DatasetComparison method handle duplicates should be in the Job class

## Expected behaviour
DatastComparison is a library part and should know nothing about writing anything anywhere. If there is duplicity it should return an issue, not handle it.

### PR DESCRIPTION
**Pull request by Zejnilovic**
### Description
Removed the duplicate writing feature. Realized that this made no sense to have / did not fit into the scope of things making DataSetComparison a swiss knife for no reason.

### Previous behaviour
On duplicate data, DatasetComparison wrote out rows of differences into a separate dataset

### Current behaviour
On duplicate data, DatasetComparison throws an error saying how many differences there are.

### Modules affected
- [x] DatasetComparison
- [ ] InfoFileComparison
- [ ] E2ERunner

### Other
- [ ] Has new configs 
- [ ] Requires Docs update
- [ ] Introduces new logs
- [ ] Introduces new error messages

Fixes #83

### CODE REVIEW

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparison.scala [hunk 1]
```diff
@@ -166,22 +166,13 @@ class DatasetComparison(cliOptions: CliOptions,
   }
 
   /**
-   * Handles duplicates in a sense that this method looks for them. Then based on the configuration if found, throws an
-   * error, does deduplication or just passes through.
+   * Handles duplicates in a sense that this method looks for them based on a primary key. Then based on the
+   * configuration, if found, throws an error.
```
Comment (benedeki) [inline datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparison.scala]:
```suggestion
   * Counts duplicates within both provided dataframes based on the primary key. Then depending on the
   * configuration, if any duplicate is found, throws an error.
```

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparison.scala [hunk 2]
```diff
@@ -166,22 +166,13 @@ class DatasetComparison(cliOptions: CliOptions,
...
    *
    * @param dfsWithKey DataFrame pair where both have appended unique key
-   * @return
+   * @return A Pair for comparison counts
    */
   private def handleDuplicates(dfsWithKey: ComparisonPair[DataFrame], cmpUniqueColumn: String): ComparisonPair[Long] = {
```
Comment (benedeki) [inline datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparison.scala:175]: I would wonder why input both dataframes in comparison as a pair. Has no functional reason, just can confuse...

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/Exceptions.scala [hunk 3]
```diff
@@ -56,8 +56,11 @@ final case class BadProvidedSchema(refPath: String,
        |$diffSchema""".stripMargin,
     cause)
 
-final case class DuplicateRowsInDF(path: String)
-  extends DatasetComparisonException(s"Provided dataset has duplicate rows. Specific rows written to $path")
+final case class DuplicateRowsInDF(countRef: Long, countNew: Long)
+  extends DatasetComparisonException(
+    s"""Provided datasets have duplicate rows.
+       |Reference Dataset has $countRef
+       |New Dataset has $countNew""".stripMargin)
```
Comment (benedeki) [inline datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/Exceptions.scala]:
```suggestion
       |Reference Dataset has $countRef duplicates
       |New Dataset has $countNew""".stripMargin) duplicates
```
Having just the number reads little strangely.

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparison.scala (hunk 2 above)
Comment (Zejnilovic) [reply datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparison.scala:175]: This was decided before the 0.2.0 release. That since we handle everything in a pair, we created a `ComparisonPair` case class to move stuff around. The clutter created from moving around multiple alone pairs and was much worse.

`ComparisonPair` on the other hand forces you to always use the correct pair of data. Be it Long, DataFrame or others. It actually made coding for me quite easier.

Comment (benedeki) [reply datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparison.scala:175]: OK, fair enough

**Review by benedeki — DISMISSED** [review]

**Review by benedeki — APPROVED** [review]
