### PR TITLE
54 Fix metrics writing to local FS

### LINKED ISSUE #54: _METRICS are not written to HDFS but to local FS
## Describe the bug
_METRICS are not written to HDFS but to local FS

**class**: DatasetComparisonJob
**method**: writeMetricsToFile

### PR DESCRIPTION
**Pull request by Zejnilovic**
Closes #54

### CODE REVIEW

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala [hunk 1]
```diff
@@ -112,14 +111,13 @@ object DatasetComparisonJob {
...
-  private def writeMetricsToFile(result: ComparisonResult, fileName: String): Unit = {
-    new File(fileName).mkdirs()
-    val writer = new PrintWriter(s"$fileName/_METRICS")
-    try {
-      writer.write(result.getJsonMetadata)
-    } finally {
-      writer.close()
-    }
+  private def writeMetricsToFile(result: ComparisonResult, fileName: String)(implicit sparkSession: SparkSession): Unit = {
+    val path = new Path(s"$fileName/_METRICS")
```
Comment (yruslan) [inline datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]:
```suggestion
    val path = new Path(fileName, "_METRICS")
```

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala [hunk 2]
```diff
@@ -112,14 +111,13 @@ object DatasetComparisonJob {
...
+    val fs = FileSystem.get(sparkSession.sparkContext.hadoopConfiguration)
+
+    val v = fs.create(path)
```
Comment (yruslan) [inline datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]: - `fs.create` can throw exceptions too.
- `v` is an odd name for a file output stream. You can use `out` or `fout`, for instance.

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala [hunk 3]
```diff
@@ -112,14 +111,13 @@ object DatasetComparisonJob {
...
+    try { v.write(result.getJsonMetadata.getBytes) }
```
Comment (yruslan) [inline datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]: `All this is optional`
Just a personal taste. I try to avoid one-liners like this. Harder to place a breakpoint. Although in IDEA it is still quite easy.
```scala
try {
    v.write(result.getJsonMetadata.getBytes)
}
```

But overall, I'd do things a little differently. Java & Scala have concepts of Input/Output streams and Readers/Writers. The difference is that Input/Output streams are designed for binary data while readers and writers are designed for text data. Readers and Writers have more control over text encoding, for instance.
So I'd write something like this (haven't tested it):
```scala
try {
    val pw = new PrintWriter(v, true)
    pw.print(result.getJsonMetadata)
    pw.close
}
```

File: utils/src/main/scala/za/co/absa/hermes/utils/SparkTestBase.scala [hunk 4]
```diff
@@ -30,5 +30,6 @@ trait SparkTestBase { self =>
     .config("spark.driver.bindAddress", "127.0.0.1")
     .config("spark.driver.host", "127.0.0.1")
     .config("spark.sql.hive.convertMetastoreParquet", false)
+    .config("fs.defaultFS","file:/")
```
Comment (yruslan) [inline utils/src/main/scala/za/co/absa/hermes/utils/SparkTestBase.scala:33]: Just curious. What does this do?

**Review by yruslan — COMMENTED** [review]
Looks good. Just a couple of optional suggestions.

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala (hunk 3 above)
Comment (yruslan) [reply datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]: But `.getBytes()` is fine too, even easier to read. Just add the charset:
```scala
v.write(result.getJsonMetadata.getBytes(StandardCharsets.UTF_8))
```

File: utils/src/main/scala/za/co/absa/hermes/utils/SparkTestBase.scala (hunk 4 above)
Comment (Zejnilovic) [reply utils/src/main/scala/za/co/absa/hermes/utils/SparkTestBase.scala:33]: This makes the test actually use local filesystem and not a running HDFS.

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala (hunk 2 above)
Comment (Zejnilovic) [reply datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]: > fs.create can throw exceptions too.

I might remember this wrongly but does it leave the stream open? If it fails in creation/opening it's "fine" and throws a proper error of not being able to.

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala (hunk 3 above)
Comment (Zejnilovic) [reply datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]: This is not optional. This is a great lecture. Thank you.

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala (hunk 2 above)
Comment (yruslan) [reply datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]: I agree that if the desired behavior is to pass through the exception if `.create()` throws than this implementation is completely correct.

Here is the Java approach to managing resources: https://www.baeldung.com/java-try-with-resources
But if I remember correctly this does not work in Scala. That's why @wajda created [ARMImplicits](https://github.com/AbsaOSS/atum/blob/master/atum/src/main/scala/za/co/absa/atum/utils/ARMImplicits.scala). 

But I didn't find its usage in Enceladus so probably we might not go that far,

**Review by yruslan — APPROVED** [review]
Cool

File: datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala (hunk 2 above)
Comment (Zejnilovic) [reply datasetComparison/src/main/scala/za/co/absa/hermes/datasetComparison/DatasetComparisonJob.scala]: I just realised I have `usingFile` [here](https://github.com/AbsaOSS/hermes/blob/develop/utils/src/main/scala/za/co/absa/hermes/utils/FileReader.scala#L37), which seems the same, but I only use it for reading. Maybe let's chat in the office.
